# Simple test config
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: '<script>alert("XSS Test")</script>'
