title: "Security Test"
description: "Testing GitHub Pages"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART"]

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    default_lang: javascript
    css_class: 'syntax'
